services:
  screenstream-web:
    build:
      context: ./web
    container_name: screenstream-web-unified
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:80"

  screenstream-signaling:
    build:
      context: ./signaling
    container_name: screenstream-signaling-unified
    restart: unless-stopped
    ports:
      - "127.0.0.1:8091:8080"
